### PR TITLE
Switch exercise

### PR DESCRIPTION
**Pull request by Ahmed-Elbessfy**
- Add If-else long example and its alternative with Switch
- Explain how Switch really works

### CODE REVIEW

**Comment by Swap76** [comment]
@Ahmed-Elbessfy The switch.md is info file so there is already a file for switch case in docs/JavaScript_Basics names switchcase.md you can append the extra info that you have their

About the foreach.md, it is exercise file right so it should have to be in docs/Exercise/JavaScript_Basics

**Comment by Ahmed-Elbessfy** [comment]
Actually that's weird. This change was on my local machine and didn't appear on my forked repository.
Second thing: switchcase.md file contains some explanation but not a complete one and comparing the two files will waste time so, I suggest that I copy my code inside the file if it is ok for you.

**Comment by Ahmed-Elbessfy** [comment]
And About foreach file: there is already a for_each.md file with explanation inside. Do you want me to edit or override its content?

**Comment by Swap76** [comment]
@Ahmed-Elbessfy Sorry I thought that you are adding the exercise question. Now I realized that there is very less info in foreach.md file JavaScript File

**Comment by Swap76** [comment]
> Actually that's weird. This change was on my local machine and didn't appear on my forked repository.
> Second thing: switchcase.md file contains some explanation but not a complete one and comparing the two files will waste time so, I suggest that I copy my code inside the file if it is ok for you.

Cool, Go ahead with it :-)

**Comment by Swap76** [comment]
@Ahmed-Elbessfy The work you have done for the project is highly appreciated. Thanks :-)

Looking forward to working with you on my new project related to Deno https://github.com/Swap76/Learn-Deno/ and together making this better.

Star to the repo is highly appreciated.

**Pull request closed without merging**
