### PR TITLE
Add Exercise Questions for Filters

### PR DESCRIPTION
**Pull request by MoisesTR**

### CODE REVIEW

**Comment by Swap76** [comment]
@MoisesTR If you have any suggestions or improvements in any other files also feel free to make it

**Comment by MoisesTR** [comment]
@Swap76 Ok dude :)

**Comment by MoisesTR** [comment]
> @MoisesTR If you have any suggestions or improvements in any other files also feel free to make it

Ok dude :)

**Comment by MoisesTR** [comment]
> @Swap76  Ok dude :)

**Comment by Swap76** [comment]
@MoisesTR The work you have done for the project is highly appreciated. Thanks :-)

Looking forward to working with you on my new project related to Deno https://github.com/Swap76/Learn-Deno/ and together making this better.

Star to the repo is highly appreciated.

**Pull request merged**
