### PR TITLE
Added Comparison operators

### PR DESCRIPTION
**Pull request by Tamy123**
There was already a well explained .md file for this topic so i just added the .js file :)

### CODE REVIEW

**Comment by Tamy123** [comment]
Please review and merge :)

**Comment by Tamy123** [comment]
Thanks alot man for appreciating the work :)

**Comment by Swap76** [comment]
@Tamy123  It was great working with you.

Looking forward to working with you :-)

Star to the repo is highly appreciated.

**Comment by Tamy123** [comment]
Sure bro :)

**Comment by Swap76** [comment]
@Tamy123 The work you have done for the project is highly appreciated. Thanks :-)

Looking forward to working with you on my new project related to Deno https://github.com/Swap76/Learn-Deno/ and together making this better.

Star to the repo is highly appreciated.

**Pull request merged**
