### PR TITLE
update Boolean.md file to contain exercise examples

### PR DESCRIPTION
**Pull request by anuk79**

### CODE REVIEW

**Comment by anuk79** [comment]
@Swap76 Kindly review

**Comment by anuk79** [comment]
@Swap76 done changes as suggested

**Comment by Swap76** [comment]
@anuk79 It was great working with you.

Looking forward to working with you :-)

Star to the repo is highly appreciated.

**Comment by Swap76** [comment]
@anuk79 The work you have done for the project is highly appreciated. Thanks :-)

Looking forward to working with you on my new project related to Deno https://github.com/Swap76/Learn-Deno/ and together making this better.

Star to the repo is highly appreciated.

**Pull request merged**
