### PR TITLE
Added Set object documentation and examples

### PR DESCRIPTION
**Pull request by fcosueza**
I've added the documentation and examples files for Set object.

### CODE REVIEW

**Comment by fcosueza** [comment]
Thanks you!!  :smiley:

**Comment by Swap76** [comment]
@fcosueza The work you have done for the project is highly appreciated. Thanks :-)

Looking forward to working with you on my new project related to Deno https://github.com/Swap76/Learn-Deno/ and together making this better.

Star to the repo is highly appreciated.

**Comment by fcosueza** [comment]
I really appreciate it, but for now, I'm a little bit busy. As soon as time allows me, I'll participate in your new project. :smiley:

**Comment by Swap76** [comment]
@fcosueza that will be great :-)

**Pull request merged**
