### PR TITLE
Added a redis.js file and a redis.md file

### PR DESCRIPTION
**Pull request by Rudy-Menekam**
added a redis.md in the doc/javascript_advance and an empty redis.js in the javascript_advance

### CODE REVIEW

**Comment by Rudy-Menekam** [comment]
yes @Swap76  you can create another issue for that please

**Comment by Swap76** [comment]
@Rudy-Menekam It was great working with you.

Looking forward to working with you :-)

Star to the repo is highly appreciated.

**Comment by Rudy-Menekam** [comment]
thank you @Swap76

**Comment by Swap76** [comment]
@Rudy-Menekam The work you have done for the project is highly appreciated. Thanks :-)

Looking forward to working with you on my new project related to Deno https://github.com/Swap76/Learn-Deno/ and together making this better.

Star to the repo is highly appreciated.

**Pull request merged**
