### PR TITLE
Added looping-an-object

### PR DESCRIPTION
**Pull request by hieetesh**
Hi, I have explained how to loop through objects in Javascript. When I started coding, I had a lot of difficulty to find a way to loop through objects. Here, I have explained the simplest way. I hope you like it. Cheers :)

### CODE REVIEW

**Comment by Swap76** [comment]
Hey @hieetesh sorry from my side. 

I got confused Great work :-)

**Comment by hieetesh** [comment]
Sure....I will add map and filter too.

**Comment by Swap76** [comment]
@hieetesh Some one else is adding that as you are working with objects that person is working on filtering arrays you can see #37

**Comment by hieetesh** [comment]
Okay. Can I add splice and slice?
Also please merge my looping-an-object. Thank you :)

**Comment by Swap76** [comment]
@hieetesh looping an object is merged already

Yes I will be creating the issue ASAP comment there so that I can assign the issue and track the progress

**Comment by Swap76** [comment]
@hieetesh #38 is created comment ASAP there to assign you

**Comment by hieetesh** [comment]
Bro, I have commented. I will complete this asap. Thank you 😊

**Comment by Swap76** [comment]
@hieetesh The work you have done for the project is highly appreciated. Thanks :-)

Looking forward to working with you on my new project related to Deno https://github.com/Swap76/Learn-Deno/ and together making this better.

Star to the repo is highly appreciated.

**Pull request merged**
