### PR TITLE
Add document related to explaining javascript callbacks in md and js format

### PR DESCRIPTION
**Pull request by n1rna**
#21

### CODE REVIEW

**Comment by n1rna** [comment]
I used some references from MDN official docs. Other than that, I wrote all the parts on my own :D

**Comment by Swap76** [comment]
@n1rna Great then we have already added MDN as a reference in References.md

You have great explanation skills

Looking forward to working with you :-)

**Comment by n1rna** [comment]
Oh thanks :)
I hope so too ;)

**Comment by Swap76** [comment]
@n1rna It was great working with you.

Looking forward to working with you :-)

Star to the repo is highly appreciated.

**Comment by Swap76** [comment]
@n1rna The work you have done for the project is highly appreciated. Thanks :-)

Looking forward to working with you on my new project related to Deno https://github.com/Swap76/Learn-Deno/ and together making this better.

Star to the repo is highly appreciated.

**Pull request merged**
