### PR TITLE
Add a tutorial for switch statements

### PR DESCRIPTION
**Pull request by Wolvan**
Add the switch tutorial to Javascript basics

### CODE REVIEW

**Comment by Wolvan** [comment]
Sorry about that, I accidentally put the file in the wrong directory. This was meant to go into Javascript_Basics

**Comment by Swap76** [comment]
@Wolvan The info about Switch exists in the docs/JavaScript_Basics you can append the file with what is not there

**Comment by Swap76** [comment]
@Wolvan It was great working with you.

Looking forward to working with you :-)

Star to the repo is highly appreciated.

**Comment by Wolvan** [comment]
I can probably write one or two more guides later. Any preference on what?

**Comment by Swap76** [comment]
@Wolvan You can add Exercise Question for JavaScript Advance. As we to need work on that also it will be super cool if you start the foundation so that I can describe in the issue, How the Exercises should be

**Comment by Swap76** [comment]
@Wolvan The work you have done for the project is highly appreciated. Thanks :-)

Looking forward to working with you on my new project related to Deno https://github.com/Swap76/Learn-Deno/ and together making this better.

Star to the repo is highly appreciated.

**Pull request merged**
