### PR TITLE
Feat add doc

### PR DESCRIPTION
**Pull request by Aman22sharma**
#5 
Added hoisting concept of JavaScript

### CODE REVIEW

**Comment by Swap76** [comment]
@Aman22sharma It was great working with you.

Looking forward to working with you :-)

Star to the repo is highly appreciated.

**Comment by Aman22sharma** [comment]
OK thank you

**Comment by Swap76** [comment]
@Aman22sharma The work you have done for the project is highly appreciated. Thanks :-)

Looking forward to working with you on my new project related to Deno https://github.com/Swap76/Learn-Deno/ and together making this better.

Star to the repo is highly appreciated.

**Comment by Aman22sharma** [comment]
Ok sure I will love to work with you 
Thank you

**Pull request merged**
