### PR TITLE
Edit for_each.md content(requested)

### PR DESCRIPTION
**Pull request by Ahmed-Elbessfy**
Apply requested editing
- edit for_each.md file content in docs/JavaScript_Basics folder
- remove forEach.js & for_each.js from JavaScript_Basics folder
as they have no use anymore

### CODE REVIEW

**Comment by Ahmed-Elbessfy** [comment]
I have applied requested changes and pushed them but nothing showed in my forked repo. check for them in the original repo.

**Comment by Swap76** [comment]
@Ahmed-Elbessfy The changes are directly getting pushed to the PR that's cool just the for_each.js is still not restored

**Comment by Swap76** [comment]
@Ahmed-Elbessfy Hey I think your repo is deleted.

Maybe you have settings of deleting repo after a PR is merged Because your repo from which the PR is made in not there on github

**Comment by Ahmed-Elbessfy** [comment]
That's wierd!! I don't know how to help but any way all changes concerning foreach.js and foreach.md are now in this pull request.

**Comment by Ahmed-Elbessfy** [comment]
Can't you check and merge it ?

**Comment by Swap76** [comment]
@Ahmed-Elbessfy The work you have done for the project is highly appreciated. Thanks :-)

Looking forward to working with you on my new project related to Deno https://github.com/Swap76/Learn-Deno/ and together making this better.

Star to the repo is highly appreciated.

**Comment by Ahmed-Elbessfy** [comment]
Well, Thanks for your trust. But I don't anything about Deno so I am not able to make a tutorial about it. Sorry for that.

**Pull request merged**
