### PR TITLE
Added pop, shift, length, delete - Add remaining array methods in Array in JavaScript #119

### PR DESCRIPTION
**Pull request by Venkat230407**
Check and let me know

### CODE REVIEW

**Comment by hakymulla** [comment]
The methods to the array passed the test

**Comment by Swap76** [comment]
@hakymulla thanks for reviewing the PR

**Comment by Swap76** [comment]
@Venkat230407  It was great working with you.

Looking forward to working with you :-)

Star to the repo is highly appreciated.

**Comment by Swap76** [comment]
@Venkat230407 The work you have done for the project is highly appreciated. Thanks :-)

Looking forward to working with you on my new project related to Deno https://github.com/Swap76/Learn-Deno/ and together making this better.

Star to the repo is highly appreciated.

**Pull request merged**
