### PR TITLE
update higher_order_functions.md

### PR DESCRIPTION
**Pull request by anuk79**
updated the higher_order_functions file to contain a basic tutorial flow for beginners

### CODE REVIEW

**Comment by anuk79** [comment]
@Swap76 Hi, kindly review. I am not able to add you as a reviewer.

**Comment by anuk79** [comment]
@Swap76 I have reverted the delete of higher_order_functions.js file. Please review

**Comment by Swap76** [comment]
@anuk79 It was great working with you.

Looking forward to working with you :-)

Star to the repo is highly appreciated.

**Comment by anuk79** [comment]
@Swap76 Thanks... it was great working with you too. Looking forward to contributing more to the repo since it's a good cause.

**Comment by Swap76** [comment]
@anuk79 The work you have done for the project is highly appreciated. Thanks :-)

Looking forward to working with you on my new project related to Deno https://github.com/Swap76/Learn-Deno/ and together making this better.

Star to the repo is highly appreciated.

**Pull request merged**
