### PR TITLE
ES6 way of swap ping variables added

### PR DESCRIPTION
**Pull request by fr1sk**

### CODE REVIEW

**Comment by fr1sk** [comment]
`:robot:` will just show 🤖emoji inside commit message, its funny :D
for some reason when I pull the code cookies.js are different from your master, just ignore my changes on that one.
Also, I wanted 2 separated PR's for swap values and count repeated values, but it wasn't how I expected.

**Comment by fr1sk** [comment]
@Swap76 What do I need to change to merge those on master?

**Comment by Swap76** [comment]
@fr1sk Restore the cookies.js and if you want 2 separate PR for that then you need to add some more examples of relevance else in this 1 PR only you can have both files added 

Let me know what you are going to do

**Comment by Swap76** [comment]
@fr1sk The work you have done for the project is highly appreciated. Thanks :-)

Looking forward to working with you on my new project related to Deno https://github.com/Swap76/Learn-Deno/ and together making this better.

Star to the repo is highly appreciated.

**Pull request merged**
