### PR TITLE
Build the sidebar from docs directories content

### PR DESCRIPTION
**Pull request by paullaffitte**
#136 
I had to rename several files to fit with the sidebar titles generation, and also to fit with the current naming of directories.
One issue that this feature has is that some files are empty, others are just trash or not done in any way, so the sidebar ends really crowded with a lot of useless links. Maybe we should do a little cleanup before merging this PR.

### CODE REVIEW

**Comment by Swap76** [comment]
@paullaffitte It was great working with you.

Looking forward to working with you :-)

Star to the repo is highly appreciated.

**Comment by tomanistor** [comment]
For some reason, `_sidebar.md` is not building for me. The terminal reads `Building _sidebar.md` with no errors.

**Comment by Swap76** [comment]
@paullaffitte Can you help us

**Comment by Swap76** [comment]
@paullaffitte The work you have done for the project is highly appreciated. Thanks :-)

Looking forward to working with you on my new project related to Deno https://github.com/Swap76/Learn-Deno/ and together making this better.

Star to the repo is highly appreciated.

**Pull request merged**
