### PR TITLE
Create higher_order_functions.md

### PR DESCRIPTION
**Pull request by andyhu92**
Add two simple exercises for higher-order function. For #253

### CODE REVIEW

**Comment by Swap76** [comment]
You can add the answer for the same also

**Comment by Swap76** [comment]
@andyhu92 It was great working with you.

Looking forward to working with you :-)

Star to the repo is highly appreciated.

**Comment by andyhu92** [comment]
@Swap76 Thanks, do you have a preferred place to add answers?

**Comment by Swap76** [comment]
@andyhu92 You can add the solution below the question only in .md file

**Comment by Swap76** [comment]
@andyhu92 The work you have done for the project is highly appreciated. Thanks :-)

Looking forward to working with you on my new project related to Deno https://github.com/Swap76/Learn-Deno/ and together making this better.

Star to the repo is highly appreciated.

**Pull request merged**
