### PR TITLE
Map exercise

### PR DESCRIPTION
**Pull request by Ahmed-Elbessfy**
- add array_map.md file
- explain how map() method works
- add examples

### CODE REVIEW

**Comment by Ahmed-Elbessfy** [comment]
Sure But I will do it tomorrow if it is ok

**Comment by Swap76** [comment]
@Ahmed-Elbessfy Cool

**Comment by Ahmed-Elbessfy** [comment]
Well, I have a problem. 
I make changes and push it to my repository but it does not appear on my repository
Can you help with this ?

**Comment by Swap76** [comment]
I think there is some issue with your remote repo there one simple thing you can save the files that you have added or changed 

fork my repo again the clone the latest repo as there will be a lot changes in these days

So their add the changed files and then add, commit, push there and make a PR

**Comment by Swap76** [comment]
@Ahmed-Elbessfy The work you have done for the project is highly appreciated. Thanks :-)

Looking forward to working with you on my new project related to Deno https://github.com/Swap76/Learn-Deno/ and together making this better.

Star to the repo is highly appreciated.

**Pull request closed without merging**
