### PR TITLE
Getting a nasa image from Nasa Api 

### PR DESCRIPTION
**Pull request by RahulBudhraj**
Making an Https request on Nasa Api and getting an image from it.

### CODE REVIEW

**Comment by RahulBudhraj** [comment]
> Hey @RahulBudhraj,
> 
> Great Work from your side still need following changes
> 
> * Please use ES6 syntax
> * Add Comments in the file
> * The formating should be proper ex. remove unnecessary line breaks etc

**Comment by RahulBudhraj** [comment]
> Hey @Swap76 
> Changes have been made.

**Comment by RahulBudhraj** [comment]
> Hey @Swap76,
> Done.

**Comment by RahulBudhraj** [comment]
> Hey @Swap76 I have added the output in file.jpg

**Comment by Swap76** [comment]
Yes merged the pull request

**Comment by Swap76** [comment]
@RahulBudhraj  It was great working with you.

Looking forward to working with you :-)

Star to the repo is highly appreciated.

**Comment by RahulBudhraj** [comment]
> @Swap76 Likewise mate :)
>Yes definitely, I would love to work with you in the future.

**Comment by Swap76** [comment]
@RahulBudhraj The work you have done for the project is highly appreciated. Thanks :-)

Looking forward to working with you on my new project related to Deno https://github.com/Swap76/Learn-Deno/ and together making this better.

Star to the repo is highly appreciated.

**Pull request merged**
